// GeneralMusic pRP8 keyboard matrix mapping
//
// Scanning pattern:
// - KD0..KD7 are used as outputs (columns)
// - MK0..MK10 and BR0..BR10 are used as inputs (rows)
// - The order below follows the same philosophy as the maudio_keystation88ii model:
//   for each row (MKx / BRx) we walk through all KD0..KD7 columns.
//
// Result:
// - 88 keys = 11 rows × 8 columns
// - First block (MK0/BR0) = lowest notes (starting at A0),
//   last block (MK10/BR10) = highest notes (ending on C8).
//
// MAKE CONTACTS (MK) – velocity start

// MK0 – first 8 keys
PINS(PIN_KD0, PIN_MK0)
PINS(PIN_KD1, PIN_MK0)
PINS(PIN_KD2, PIN_MK0)
PINS(PIN_KD3, PIN_MK0)
PINS(PIN_KD4, PIN_MK0)
PINS(PIN_KD5, PIN_MK0)
PINS(PIN_KD6, PIN_MK0)
PINS(PIN_KD7, PIN_MK0)

// MK1
PINS(PIN_KD0, PIN_MK1)
PINS(PIN_KD1, PIN_MK1)
PINS(PIN_KD2, PIN_MK1)
PINS(PIN_KD3, PIN_MK1)
PINS(PIN_KD4, PIN_MK1)
PINS(PIN_KD5, PIN_MK1)
PINS(PIN_KD6, PIN_MK1)
PINS(PIN_KD7, PIN_MK1)

// MK2
PINS(PIN_KD0, PIN_MK2)
PINS(PIN_KD1, PIN_MK2)
PINS(PIN_KD2, PIN_MK2)
PINS(PIN_KD3, PIN_MK2)
PINS(PIN_KD4, PIN_MK2)
PINS(PIN_KD5, PIN_MK2)
PINS(PIN_KD6, PIN_MK2)
PINS(PIN_KD7, PIN_MK2)

// MK3
PINS(PIN_KD0, PIN_MK3)
PINS(PIN_KD1, PIN_MK3)
PINS(PIN_KD2, PIN_MK3)
PINS(PIN_KD3, PIN_MK3)
PINS(PIN_KD4, PIN_MK3)
PINS(PIN_KD5, PIN_MK3)
PINS(PIN_KD6, PIN_MK3)
PINS(PIN_KD7, PIN_MK3)

// MK4
PINS(PIN_KD0, PIN_MK4)
PINS(PIN_KD1, PIN_MK4)
PINS(PIN_KD2, PIN_MK4)
PINS(PIN_KD3, PIN_MK4)
PINS(PIN_KD4, PIN_MK4)
PINS(PIN_KD5, PIN_MK4)
PINS(PIN_KD6, PIN_MK4)
PINS(PIN_KD7, PIN_MK4)

// MK5
PINS(PIN_KD0, PIN_MK5)
PINS(PIN_KD1, PIN_MK5)
PINS(PIN_KD2, PIN_MK5)
PINS(PIN_KD3, PIN_MK5)
PINS(PIN_KD4, PIN_MK5)
PINS(PIN_KD5, PIN_MK5)
PINS(PIN_KD6, PIN_MK5)
PINS(PIN_KD7, PIN_MK5)

// MK6
PINS(PIN_KD0, PIN_MK6)
PINS(PIN_KD1, PIN_MK6)
PINS(PIN_KD2, PIN_MK6)
PINS(PIN_KD3, PIN_MK6)
PINS(PIN_KD4, PIN_MK6)
PINS(PIN_KD5, PIN_MK6)
PINS(PIN_KD6, PIN_MK6)
PINS(PIN_KD7, PIN_MK6)

// MK7
PINS(PIN_KD0, PIN_MK7)
PINS(PIN_KD1, PIN_MK7)
PINS(PIN_KD2, PIN_MK7)
PINS(PIN_KD3, PIN_MK7)
PINS(PIN_KD4, PIN_MK7)
PINS(PIN_KD5, PIN_MK7)
PINS(PIN_KD6, PIN_MK7)
PINS(PIN_KD7, PIN_MK7)

// MK8
PINS(PIN_KD0, PIN_MK8)
PINS(PIN_KD1, PIN_MK8)
PINS(PIN_KD2, PIN_MK8)
PINS(PIN_KD3, PIN_MK8)
PINS(PIN_KD4, PIN_MK8)
PINS(PIN_KD5, PIN_MK8)
PINS(PIN_KD6, PIN_MK8)
PINS(PIN_KD7, PIN_MK8)

// MK9
PINS(PIN_KD0, PIN_MK9)
PINS(PIN_KD1, PIN_MK9)
PINS(PIN_KD2, PIN_MK9)
PINS(PIN_KD3, PIN_MK9)
PINS(PIN_KD4, PIN_MK9)
PINS(PIN_KD5, PIN_MK9)
PINS(PIN_KD6, PIN_MK9)
PINS(PIN_KD7, PIN_MK9)

// MK10 – last 8 keys
PINS(PIN_KD0, PIN_MK10)
PINS(PIN_KD1, PIN_MK10)
PINS(PIN_KD2, PIN_MK10)
PINS(PIN_KD3, PIN_MK10)
PINS(PIN_KD4, PIN_MK10)
PINS(PIN_KD5, PIN_MK10)
PINS(PIN_KD6, PIN_MK10)
PINS(PIN_KD7, PIN_MK10)

// BREAK CONTACTS (BR) – velocity end

// BR0 – same 8 keys as MK0
PINS(PIN_KD0, PIN_BR0)
PINS(PIN_KD1, PIN_BR0)
PINS(PIN_KD2, PIN_BR0)
PINS(PIN_KD3, PIN_BR0)
PINS(PIN_KD4, PIN_BR0)
PINS(PIN_KD5, PIN_BR0)
PINS(PIN_KD6, PIN_BR0)
PINS(PIN_KD7, PIN_BR0)

// BR1
PINS(PIN_KD0, PIN_BR1)
PINS(PIN_KD1, PIN_BR1)
PINS(PIN_KD2, PIN_BR1)
PINS(PIN_KD3, PIN_BR1)
PINS(PIN_KD4, PIN_BR1)
PINS(PIN_KD5, PIN_BR1)
PINS(PIN_KD6, PIN_BR1)
PINS(PIN_KD7, PIN_BR1)

// BR2
PINS(PIN_KD0, PIN_BR2)
PINS(PIN_KD1, PIN_BR2)
PINS(PIN_KD2, PIN_BR2)
PINS(PIN_KD3, PIN_BR2)
PINS(PIN_KD4, PIN_BR2)
PINS(PIN_KD5, PIN_BR2)
PINS(PIN_KD6, PIN_BR2)
PINS(PIN_KD7, PIN_BR2)

// BR3
PINS(PIN_KD0, PIN_BR3)
PINS(PIN_KD1, PIN_BR3)
PINS(PIN_KD2, PIN_BR3)
PINS(PIN_KD3, PIN_BR3)
PINS(PIN_KD4, PIN_BR3)
PINS(PIN_KD5, PIN_BR3)
PINS(PIN_KD6, PIN_BR3)
PINS(PIN_KD7, PIN_BR3)

// BR4
PINS(PIN_KD0, PIN_BR4)
PINS(PIN_KD1, PIN_BR4)
PINS(PIN_KD2, PIN_BR4)
PINS(PIN_KD3, PIN_BR4)
PINS(PIN_KD4, PIN_BR4)
PINS(PIN_KD5, PIN_BR4)
PINS(PIN_KD6, PIN_BR4)
PINS(PIN_KD7, PIN_BR4)

// BR5
PINS(PIN_KD0, PIN_BR5)
PINS(PIN_KD1, PIN_BR5)
PINS(PIN_KD2, PIN_BR5)
PINS(PIN_KD3, PIN_BR5)
PINS(PIN_KD4, PIN_BR5)
PINS(PIN_KD5, PIN_BR5)
PINS(PIN_KD6, PIN_BR5)
PINS(PIN_KD7, PIN_BR5)

// BR6
PINS(PIN_KD0, PIN_BR6)
PINS(PIN_KD1, PIN_BR6)
PINS(PIN_KD2, PIN_BR6)
PINS(PIN_KD3, PIN_BR6)
PINS(PIN_KD4, PIN_BR6)
PINS(PIN_KD5, PIN_BR6)
PINS(PIN_KD6, PIN_BR6)
PINS(PIN_KD7, PIN_BR6)

// BR7
PINS(PIN_KD0, PIN_BR7)
PINS(PIN_KD1, PIN_BR7)
PINS(PIN_KD2, PIN_BR7)
PINS(PIN_KD3, PIN_BR7)
PINS(PIN_KD4, PIN_BR7)
PINS(PIN_KD5, PIN_BR7)
PINS(PIN_KD6, PIN_BR7)
PINS(PIN_KD7, PIN_BR7)

// BR8
PINS(PIN_KD0, PIN_BR8)
PINS(PIN_KD1, PIN_BR8)
PINS(PIN_KD2, PIN_BR8)
PINS(PIN_KD3, PIN_BR8)
PINS(PIN_KD4, PIN_BR8)
PINS(PIN_KD5, PIN_BR8)
PINS(PIN_KD6, PIN_BR8)
PINS(PIN_KD7, PIN_BR8)

// BR9
PINS(PIN_KD0, PIN_BR9)
PINS(PIN_KD1, PIN_BR9)
PINS(PIN_KD2, PIN_BR9)
PINS(PIN_KD3, PIN_BR9)
PINS(PIN_KD4, PIN_BR9)
PINS(PIN_KD5, PIN_BR9)
PINS(PIN_KD6, PIN_BR9)
PINS(PIN_KD7, PIN_BR9)

// BR10 – same 8 keys as MK10
PINS(PIN_KD0, PIN_BR10)
PINS(PIN_KD1, PIN_BR10)
PINS(PIN_KD2, PIN_BR10)
PINS(PIN_KD3, PIN_BR10)
PINS(PIN_KD4, PIN_BR10)
PINS(PIN_KD5, PIN_BR10)
PINS(PIN_KD6, PIN_BR10)
PINS(PIN_KD7, PIN_BR10)

